### ISSUE TITLE
The test result is not correct

### ISSUE THREAD

**Issue by GH-HOME** [gengshan-y/high-res-stereo#1]
Hi, I run the code with this command

`CUDA_VISIBLE_DEVICES=3 python submission.py --datapath ./data-mbtest/   --outdir ./mboutput --loadmodel ./weights/final-768px.tar  --testres 1 --clean 0.8 --max_disp -1`

I get results as following.
[https://ibb.co/LRkRMh5](url)

Which is not corresponding to the results shown in the Readme file.

Can you obtain the same result under current pre-trained model?

**Comment by GH-HOME** [comment]
CrusadeP-disp.png
![CrusadeP-disp](https://user-images.githubusercontent.com/18206839/60023306-8594db80-96d0-11e9-949a-f9dbf8296713.png)
CrusadeP-ent.png
![CrusadeP-ent](https://user-images.githubusercontent.com/18206839/60023323-8d548000-96d0-11e9-90de-ea85bd4f8753.png)

**Comment by SorcererX** [comment]
I am also unable to get similar results to those in the Readme file.

**Comment by gengshan-y** [comment]
Which version of torchvision are you using? It may get corrupted results due to API change.
If you are not using torchvision=0.2.0, you could try pip install torchvision==0.2.0

**Comment by GH-HOME** [comment]
> Which version of torchvision are you using? It may get corrupted results due to API change.
> If you are not using torchvision=0.2.0, you could try pip install torchvision==0.2.0

Yes， you are right. Also, we need to make sure the torch version == 0.4.0.
Now the result is exactly the same with those in the README file.

**Comment by SorcererX** [comment]
If the preprocess.py is modified slightly, like:
https://github.com/SorcererX/high-res-stereo/blob/master/utils/preprocess.py

I am able to achieve the correct result with PyTorch 0.4.0, 0.4.1, 1.0.1 and 1.1.0 as well as torchvision 0.2.0, 0.2.1 and 0.3.0

**Comment by SorcererX** [comment]
The broken torchvision 0.2.1 behavior can be reproduced by using:
torch.from_numpy( pic.transpose((2, 0, 1)))
instead of:
torch.from_numpy( pic.transpose((2, 0, 1))).float().div(255)

**Comment by gengshan-y** [comment]
Hi SorcererX, good catch! Do you want to send a pull request?
