### ISSUE TITLE
Question about disparity regression

### ISSUE THREAD

**Issue by gallenszl** [gengshan-y/high-res-stereo#10]
Hi, I find that in the disparity regression step, you set 
self.disp_reg8 = disparityregression(self.maxdisp,16)
In my opinion, self.disp_reg8 is used for disparity regression of cost3(1/8 resolution of the origin),so the divisor should be 8 rather than 16. Can you tell me why you choose 16 as divisor?
On the other hand, I am very interested about the reason why  you don't select to upsample the disparity to the max_disp just like PSMNet. Thanks.

**Comment by gengshan-y** [comment]
Hi, the spatial resolution, i.e., (height,width) of the last scale is 1/8, however, the disparity resolution is 1/16. By doing this, you're saving a decent amount of memory and able to use a larger batch in training. And from our experience, there is no significant loss of accuracy. The same "memory argument" holds for your second question.

**Comment by gallenszl** [comment]
Thank you for your reply. But I still a little confused with this question, actually when you construct cost volume you set 
feat3 = self.feature_vol(conv10, conv11, self.maxdisp//8)  
doesn't it mean the disparity resolution is 1/8 of max disparity?

**Comment by gengshan-y** [comment]
Hi, the cost volume is constructed in 1/8 resolution, but further processed with a strided 3D convolution, which reduces the resolution to 1/16.
https://github.com/gengshan-y/high-res-stereo/blob/d24a58ad99876a51be49ff5e6cc5271cf7664e33/models/hsm.py#L32
