### ISSUE TITLE
Why divide by 256 for png files in disparity_loader in MiddleburyLoader.py?

### ISSUE THREAD

**Issue by yangjzx** [gengshan-y/high-res-stereo#15]
![image](https://user-images.githubusercontent.com/51399644/79047401-e03ff980-7c48-11ea-844d-95d72672f0ee.png)
As shown in the image above, why should the disparity loaded from png files divide by 256? Is it a special requirement for some datasets? Or the ground truth disparity values should be normed to a region？

**Comment by gengshan-y** [comment]
This is a dataset specific issue. As for KITTI, disparity is multiplied by 256 and stored as 16bit integer ".png" images.
