### ISSUE TITLE
Depth Estimation

### ISSUE THREAD

**Issue by skyhehe123** [gengshan-y/high-res-stereo#17]
Hi, 
I use your pre-trained model and convert the disp to depth with the following formula,
Depth = f * baseline / pred_disp, where the f and baseline are directly obtained from the calibration file. 
When I unproject the depth image to the point cloud, I found the result is no satisfactory. 
Do I go sth wrong when calculating the depth map?
![Screenshot from 2020-05-31 20-58-39](https://user-images.githubusercontent.com/22584454/83352980-f6815080-a381-11ea-80b8-4ad2665296bf.png)

**Comment by gengshan-y** [comment]
Which tool did you use for vis? I thought the cv toolkit uses disparity images as input? It will automatically convert disparity to depth for you.

**Comment by aihaoc** [comment]
> Which tool did you use for vis? I thought the cv toolkit uses disparity images as input? It will automatically convert disparity to depth for you.

hi，How did you get the camera parameters and correct the image

**Comment by gengshan-y** [comment]
Camera parameters are provided by the Middlebury dataset: https://vision.middlebury.edu/stereo/

**Comment by aihaoc** [comment]
> Camera parameters are provided by the Middlebury dataset: https://vision.middlebury.edu/stereo/

The file in high-res-stereo/data-mbtest/0593_8_0661_1/  isn't meant to be a Middlebury dataset, is it? How did Calib.txt come into being?

**Comment by gengshan-y** [comment]
Pair 0593_8_0661_1 is taken from the "Gangnam Style" sequence in [open4d](https://www.cs.cmu.edu/~aayushb/Open4D/) and [Spatiotemporal BA](https://www.cs.cmu.edu/~ILIM/projects/IM/STBA/). A spatiotemporal bundle adjustment method is used there. Please refer to the paper for details. 

I believe classic SfM (e.g. [COLMAP](https://colmap.github.io/)) can also be applied to get intrinsics/extrinsics for many use cases.

**Comment by nnop** [comment]
Hi, Gengshan.
Just found you refered the [Spatiotemporal BA](https://www.cs.cmu.edu/~ILIM/projects/IM/STBA/) method. Did you have any reference implementation.
