### ISSUE TITLE
About the weights

### ISSUE THREAD

**Issue by Yidoudoujiang** [gengshan-y/high-res-stereo#18]
Thank you very much for your code, but I would like to ask if the weights of indoor and outdoor scenes are the same?

**Comment by gengshan-y** [comment]
The provided weights file corresponds to HSM is Tab.2. It's different from the weights file on KITTI.

**Comment by Yidoudoujiang** [comment]
Could you provide the weights file on  KITTI?

**Comment by gengshan-y** [comment]
Hi, it's just uploaded. Please check out the new readme page. 

I also want to mention that: 
1) upsampling inputs to 1.8x resolution (--testres 1.8) gives lowest validation error on KITTI. 
2) The current interface does not support data IO for KITTI benchmark, so you might want to write your own (possibly following [robust vision challenge](https://github.com/ozendelait/rvc_devkit/tree/release/stereo)). 

Thanks
