### ISSUE TITLE
How to get accurate disparity in the real world

### ISSUE THREAD

**Issue by Hahaemmm** [gengshan-y/high-res-stereo#19]
I want to make some real-world data, how to generate the corresponding ground truth of disparity?

**Comment by gengshan-y** [comment]
If I understand correctly, your goal is to generate pseudo-ground-truth using HSM, right? If so, you need to have [rectified](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga617b1685d4059c6040827800e72ad2b6) stereo pairs. This ensures correspondences lie on the horizontal scanline. [This paper](https://kai-46.github.io/DepthSensing/my_files/paper.pdf) seems to be a good reference.

**Comment by Hahaemmm** [comment]
My goal is to make an indoor stereo matching data set, but I don’t know how to make ground truth.

**Comment by Hahaemmm** [comment]
What kind of LiDAR are you using

**Comment by gengshan-y** [comment]
I don't know the exact model/version of the LiDAR sensor. It's the same type of sensor used in the [argoverse](https://www.argoverse.org/) dataset.
