### ISSUE TITLE
about the cost_volume

### ISSUE THREAD

**Issue by xubin1994** [gengshan-y/high-res-stereo#2]
Hi,I have run the code and get the same result in the paper.And I am curious about the idea to get the shape edge in HSM Net.
I have found the "real" max size of cost volume is only 1/8 resolution of the origin，but can get sharp edge in the result with simply upsample the cost volume to the origin size and following with a disparityregression step.
It is an amazing thing!because other net about stereo(for example,stereoNet) usually need an complicated step like "Guided Hierarchical Refinement" to get the sharp edge.
Can you give me some ideas to understand why  the HSM Net  can produce the sharp disp map without some complicated step?

**Comment by gengshan-y** [comment]
That's a great question! We probably forgot to mention in the paper. The straightforward answer is: If you *train* the network to up-sample predictions to be comparable with the high-res ground-truth, in the test time, it will make predictions that *can* be up-sampled to high-res while keeping details.

From a higher level, we choose not to up-sample the 1/8-res disparity maps but the cost volume, because it contains more information to support such aggressive up-sampling.

**Comment by xubin1994** [comment]
> That's a great question! We probably forgot to mention in the paper. The straightforward answer is: If you _train_ the network to up-sample predictions to be comparable with the high-res ground-truth, in the test time, it will make predictions that _can_ be up-sampled to high-res while keeping details.
> 
> From a higher level, we choose not to up-sample the 1/8-res disparity maps but the cost volume, because it contains more information to support such aggressive up-sampling.

Thank you for your reply,I noticed that you are upsampling the cost space, but I was not sure if this is the key before. Now I am going to use this idea to rewrite other networks to see if I can maintain performance while reducing the amount of parameters.Thanks again！

**Comment by xubin1994** [comment]
Yes,I tested it myself and the performance of the network on the sceneflow dataset is not as good as the middleburrry.May be caused by low resolution?My result is  as follows(frames_disparity\TRAIN\A\0008\left):
![ground_truth](https://user-images.githubusercontent.com/28856641/60556415-c85f4f00-9d73-11e9-9c10-70ee7b2690c1.png)

![HSM](https://user-images.githubusercontent.com/28856641/60556459-fb094780-9d73-11e9-9bd2-c591a12bd6e8.png)

@YuhuaXu

**Comment by YuhuaXu** [comment]
The disparity map edge looks blurred. Thanks for your test @xubin1994 . Does this test has problems? @gengshan-y

**Comment by gengshan-y** [comment]
@xubin1994 Did you up-scale the image?  For example, up-scale the image by 4 using --testres 4? In the meanwhile you may also need to specify the maximum disparity.

**Comment by xubin1994** [comment]
> @xubin1994 Did you up-scale the image? For example, up-scale the image by 4 using --testres 4? In the meanwhile you may also need to specify the maximum disparity.
I have not previously upsampled the SceneFlow dataset.And I do it up-scale the image by 2 and get a better result(the memory（11GB） of my machine is not enough for 4X upsampling).So upsampling the input image is a technical means to get a better output?
![image](https://user-images.githubusercontent.com/28856641/60560727-8d651780-9d83-11e9-8f89-53218e805f19.png)

**Comment by gengshan-y** [comment]
Yeah, the main idea of our approach is about dealing with high-res inputs, and every design choice is leaning towards high-res (about 6 Megapixel). The ideal input would be high-res images and *upsampling* is just a simple workaround for low-res inputs.
