### ISSUE TITLE
About the camera's baseline

### ISSUE THREAD

**Issue by Yidoudoujiang** [gengshan-y/high-res-stereo#21]
Hi,  @gengshan-y . What is the camera's baseline in the actual scene you test？ When I reconstructed the point cloud, it occured to 'slice'.  Is it due to a different baseline？
![7 30-issue](https://user-images.githubusercontent.com/56189843/88904071-2caa5600-d287-11ea-8224-25d593279fa0.jpg)

**Comment by gengshan-y** [comment]
Can you describe in more details? It's hard to see the problem from a point clout image. Are the objects flattened?

**Comment by Yidoudoujiang** [comment]
Thank you for reply.  The objects are not flattened.
We test `submission.py` with
`python 3.7.6
pytorch 1.0.0

--loadmodel  final-768px.tar
--testres  1
--clean  1.0
--max_disp  1280  (the size of image)`

Then using the predicted  disparity map and corrected binocular images reconstruct the  point cloud with PCL .  Our camera's baseline is 8cm. It seems the distance between "slice" is too wide.
![7 31-iss](https://user-images.githubusercontent.com/56189843/88994750-a4c25b80-d31b-11ea-9816-5b8201267853.png)

**Comment by gengshan-y** [comment]
I'm not sure how were your 3D points constructed. Depth should be computed as (baseline*focal length / disparity). Then 2D points can be converted to 3D by multiplying with the inverse of camera intrinsics: P = depth(Kinv.dot(p)).

If the overall layout is wrong, it may suggest the camera intrinsics is wrong.

**Comment by gengshan-y** [comment]
A wrong baseline would give you an up-to-scale error -- the layout is current, but 3D points were multiplied by a different scale factor.

**Comment by Yidoudoujiang** [comment]
We'll try to find out the reason, and thanks again for your response！
