### ISSUE TITLE
add_argument

### ISSUE THREAD

**Issue by sunxiuxiu** [gengshan-y/high-res-stereo#23]
parser.add_argument('--indir', type=str ,default='/ssd/carla-highres/carlaF/',
                    help='resolution')
parser.add_argument('--gtdir', type=str ,default='/ssd/carla-highres/testF/',
                    help='resolution')
请问这个路径的相关文件在哪里下载

**Comment by gengshan-y** [comment]
It's in the [HR-VS dataset ](https://drive.google.com/file/d/1SgEIrH_IQTKJOToUwR1rx4-237sThUqX/view?usp=sharing)

Also you don't need it to run evaluation.
