### ISSUE TITLE
What factors lead to good performance？

### ISSUE THREAD

**Issue by YuhuaXu** [gengshan-y/high-res-stereo#3]
Your network ranks the top end-to-end network in Middlebury Stereo. It is great! So, what do you think is the most important performance that brings good performance? It seems that data enhancement and direct matching at the highest resolution are the main factors?

Besides, up-sampling from 1/8 cost volume to 1/1 cost volume may lead to blurred edge, especially for the middle-level resolution images (e.g. 1000x1000).

**Comment by gengshan-y** [comment]
We would rank "feature volume refinement" as the most important factor, as mentioned in in Paper Sec 3.1.  It refines the low-res feature volumes with the high-res ones repeatedly, which can be thought of as refining a voxel reconstruction from coarse to fine. See diagnostic experiment results in Table 5 for other factors, including synthetic high-res dataset, data augmentation, etc. 

Please refer to #2 for your last comment. Thanks.
