### ISSUE TITLE
Some clarification in supplemental 

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [gengshan-y/high-res-stereo#32]
Hi,

I wanted the layerwise detail of Highres stereo. I got some information from Figure 6 in the supplemental material. Can you please let me know what is iconv layer? uconv is deconvolution layer in 2d and Up3d is deconvolution in 3d, I suppose.

Please clarify.

Also, is the SPP block the same as PSMNet? There are 4 pooling units 64x6, 32x32, 16x16, and 8x8 in SPP in PSMNet followed by 1x1 convolution.

**Comment by gengshan-y** [comment]
Hi, 

[iconv](https://github.com/gengshan-y/high-res-stereo/blob/1c70d5c01ae96be48a3cc34e3086f09a3600653a/models/utils.py#L33) is a standard 2Dconv+bn+relu layer. the prefix i only indicates it's applied after a up-sampling operation.

[uconv](https://github.com/gengshan-y/high-res-stereo/blob/1c70d5c01ae96be48a3cc34e3086f09a3600653a/models/utils.py#L30) is an 2D upsampling+2Dconv+bn+relu layer

[up3d](https://github.com/gengshan-y/high-res-stereo/blob/1c70d5c01ae96be48a3cc34e3086f09a3600653a/models/submodule.py#L104) is an 3D upsampling+3Dconv+bn+relu layer.

[spp layer](https://github.com/gengshan-y/high-res-stereo/blob/1c70d5c01ae96be48a3cc34e3086f09a3600653a/models/utils.py#L240) is adapted to high-res. Concatenation is replaced by sum and the pooling kernel sizes are modifed.

**Comment by Diksha-Moolchandani** [comment]
thanks a lot
