### ISSUE TITLE
data loading in Windows

### ISSUE THREAD

**Issue by diriki** [gengshan-y/high-res-stereo#34]
When running submission.py in Windows as in the first example of the [readme](https://github.com/gengshan-y/high-res-stereo#inference), no image is found.
This is because, in the [dataloader function](https://github.com/gengshan-y/high-res-stereo/blob/1c70d5c01ae96be48a3cc34e3086f09a3600653a/dataloader/listfiles.py#L12), glob retrives pathes with '\' and algorithm splits pathes on '/'.
I suggest to replace `i.split('/')[-1]` with `i.split('/')[-1].split('\\')[-1]` at [dataloader/listfiles.py, line 12](https://github.com/gengshan-y/high-res-stereo/blob/1c70d5c01ae96be48a3cc34e3086f09a3600653a/dataloader/listfiles.py#L12): with this trick it works fine in my Windows 10 PC (tested with Python 3.6 and 3.7).

**Comment by gengshan-y** [comment]
Updated, thanks for bringing up this issue.
