### ISSUE TITLE
Question about the Uncertainty Map

### ISSUE THREAD

**Issue by EmanueleGhelfi** [gengshan-y/high-res-stereo#35]
From the figure https://github.com/gengshan-y/high-res-stereo/blob/master/mboutput/CrusadeP-ent.png and also in our experiments, the uncertainty map seems to have a stripe behaviour. 
Is this an expected behaviour, or is it just an artifact?
Do you have an idea of the possible causes?

Thank you for your support.

**Comment by gengshan-y** [comment]
Hi, this stripe artifact is expected and related to the the disparity discretization. 

Such artifact happens when a pixel's actual disparity lies in between two nearby discrete disparity classes (let's call it k and k+1), in which case similar costs were assigned to disparity k and k+1, and that makes it's uncertainty appears higher than pixels whose disparity fully falls into either k or k+1. 

Hope this makes sense.

**Comment by EmanueleGhelfi** [comment]
Hi, thank you for your response!

So, the assumption here is that all pixels belonging to a stripe have a
disparity that lies between to disparities, correct?

What about calculating the entropy on a different (coarser) discretization
of the disparity? Would it help in similar cases?

I mean, in general we are not interested in masking pixels whose disparity
falls between two nearby classes, we are more interested in masking pixels
with two (or more) different disparity candidates which are distant from
each other.

Am I wrong?

**Comment by gengshan-y** [comment]
From my observation, the uncertainty of mismatches are usually much higher than the uncertainty of boundary pixels (whose disparity lies between two discrete disparity bins). By selecting a proper threshold in the example pair, we are able to only filter out mismatches.

Indeed, the lowerbound of stripe uncertainty could be approximately computed as if one assign probability 0.5 to class k and k+1 and 0 elsewhere, which is log(2). This suggests one may use a threshold greater than log(2) to not filter out pixels with stripe artifacts.

**Comment by EmanueleGhelfi** [comment]
Thank you for your support!
