### ISSUE TITLE
How to test disparity of a rectified pair stereo pairs?

### ISSUE THREAD

**Issue by CaptainEven** [gengshan-y/high-res-stereo#37]

**Comment by gengshan-y** [comment]
To run HSM on a your own data, please organize your stereo pair similar to data-mbtest/CrusadeP/ folder and follow the inference example.

For calib.txt file, only line-7 (ndisp) is used in the inference pipeline. The rest of the parameters are only useful for 3D visualization with cvlib. Please see [middlebury](https://vision.middlebury.edu/stereo/data/scenes2014/) dataset for more details.
