### ISSUE TITLE
Input to the encoder

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [gengshan-y/high-res-stereo#38]
Hi,

Is the input to the encoder H x W x 3 or H x W x 6 for two stereo images? Figure 6 in the supplementary pdf shows it to be H x W x 3.

**Comment by gengshan-y** [comment]
Hi, the input to the encoder is Bx3xHxW, where B=2 is the batch dimension. We want to independently extract features from a stereo pair with the same set of convnet filters.

**Comment by Diksha-Moolchandani** [comment]
Thanks.
But where do you combine the extracted features from the two images? From figure 2 of the main paper, the features should be combined before the decoding process. In the figure 6 of the supplementary pdf, I am not able to deduce from the parameters where the combining is being done.
 Can you please clarify?

**Comment by gengshan-y** [comment]
Hi, after feature extraction, a CxDxHxW "feature volume" is constructed from the feature maps of the stereo pair. This is done by taking the difference of features at each HxW grid point of the left-view with its D potential matches in the right-view.
Please see the [code](https://github.com/gengshan-y/high-res-stereo/blob/cb60fde567066f59caea709dca1ac26b2ea27380/models/hsm.py#L41) and Sec 3.1 Feature volumes in the paper for details.

**Comment by Diksha-Moolchandani** [comment]
thanks
