### ISSUE TITLE
Calculate depth map from disparity map

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [gengshan-y/high-res-stereo#40]
Hi,

After getting the predicted disparity https://github.com/gengshan-y/high-res-stereo/blob/master/submission.py#L132 for KITTI 2015 training images, I calculate the 3-pixel error using the formula in the kitti evaluation kit.

I found some information regarding the focal length and the baseline for kitti images here: https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L29. However, there is no information of getting depth map from disparity map on Kitti website. Can you please let me know how should I get the depth map from the disparity map pred_disp?

**Comment by gengshan-y** [comment]
Hi, you may use some functions in [pykitti](https://github.com/utiasSTARS/pykitti) to get baseline and focal length per sequence. Then, depth is simply calculated by focal_length * baseline / disparity.

**Comment by Diksha-Moolchandani** [comment]
Thanks for the reply.

If I apply this formula for all the locations in a disparity map, I will get a depth map. Can I use this directly for some object detection algorithm? If yes, can you please provide me some examples of the same?

**Comment by gengshan-y** [comment]
This is one paper I'm aware of https://mileyan.github.io/pseudo_lidar/

**Comment by Diksha-Moolchandani** [comment]
Thanks.

Yes I saw this but they convert the points to Lidar like representation. That is, along with calculating the depth, they transform the x and y also. I was wondering if only the depth map can be used in some object detection algorithm such that I do not need to transform x and y. I don't have much idea, I am just guessing if this is possible or not.
