### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by benknight135** [gengshan-y/high-res-stereo#42]
I noticed this repository uses the MIT license. Does this mean this is available for commercial use? 
I work for a stereo vision company and will be trying this out over the next few days to see how it performs (on my own time) but could see some really great uses within the company's products. We would of course credit your work if it was used.

**Comment by gengshan-y** [comment]
Hi, the code is open-sourced under MIT license. From my understanding, it is allowed to use it commercially. But there is no guarantee on the functionality. So yes, please take it as you like.
