### ISSUE TITLE
reproducing kitti weights model

### ISSUE THREAD

**Issue by ohosseini** [gengshan-y/high-res-stereo#43]
Could you please provide the training details for reproducing the kitti model?

**Comment by gengshan-y** [comment]
To reproduce the kitti model, you will need to change the dataset and set the maximum disparity to 384 (training time).

Quoting from our paper "During training time, we excluded the ETH3D and Sceneflow datasets and finetuned with Middlebury-v3, KITTI-12 and KITTI-15. At test time, we operate on image pairs up-sampled by a factor of 1.8."

**Comment by ohosseini** [comment]
Thanks for your reply!
