### ISSUE TITLE
out of memory while testing the example

### ISSUE THREAD

**Issue by zhangmaoxiansheng** [gengshan-y/high-res-stereo#6]
Hi! I want to test your example but an OOM error occured. My GPU is Nvidia 1080ti. So what is the requirement for the GPU memory?

**Comment by gengshan-y** [comment]
It depends on the resolution and maximum disparity, which can be adjusted via input parameters. 2000x3000px input with 700px maximum displacement should take less than 12GB.

Please refer to #5

**Comment by zhangmaoxiansheng** [comment]
Thx. I found that using pytorch 1.1.0 instead of pytorch 0.4 can solve the OOM error. But the dispairty result is a little different from your result.
![CrusadeP-disp](https://user-images.githubusercontent.com/22913931/62831430-9df59100-bc51-11e9-8e19-ae84a3beb41e.png)
CrusadeP-ent:
![CrusadeP-ent](https://user-images.githubusercontent.com/22913931/62831435-b5cd1500-bc51-11e9-99a9-8b0028eb1c5a.png)
There are some hole in the disparity map.Is that right?

**Comment by gengshan-y** [comment]
That looks correct. The program sets pixels with large uncertainties to inf. by default. To produce the original output, please pass “--clean -1” to the program.

**Comment by zhangmaoxiansheng** [comment]
OK! I got the same result. Thanks a lot! By the way, I am looking forward to your HS-RS dataset.
