### ISSUE TITLE
Cannot extract downloaded weights

### ISSUE THREAD

**Issue by ryx2** [gengshan-y/high-res-stereo#9]
I downloaded the weights from the link on your readme, which downloaded a .tar from a google drive share. I cannot extract this tar using any program I can find, on any OS. I think the file may be corrupt?

**Comment by ryx2** [comment]
Nevermind - looks like you link the .tar as an input to the model directly instead of extracting

**Comment by ryx2** [comment]
The model weights file extension shouldn't be .tar. this is confusing.

**Comment by SorcererX** [comment]
If you look at https://pytorch.org/tutorials/beginner/saving_loading_models.html this is actually a PyTorch convention.
So in this case, anything else than .tar would be confusing, even though I agree that the authors of PyTorch could've picked a different extension.
